/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class information_tgnet_MathKit */

#ifndef _Included_information_tgnet_MathKit
#define _Included_information_tgnet_MathKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     information_tgnet_MathKit
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_information_tgnet_MathKit_square
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
