/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class information_tgnet_StringKit */

#ifndef _Included_information_tgnet_StringKit
#define _Included_information_tgnet_StringKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     information_tgnet_StringKit
 * Method:    setNull
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_information_tgnet_StringKit_setNull
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
