/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class information_tgnet_MainActivity */

#ifndef _Included_information_tgnet_MainActivity
#define _Included_information_tgnet_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     information_tgnet_MainActivity
 * Method:    addResult
 * Signature: (I)I
 */
JNIEXPORT jdouble JNICALL Java_information_tgnet_MainActivity_addResult
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
